# Generated by Django 5.1.7 on 2025-05-27 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Guide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('biography', models.TextField()),
                ('languages', models.CharField(max_length=200)),
                ('image', models.ImageField(blank=True, null=True, upload_to='guides/')),
            ],
        ),
    ]
